---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    exclude_fingerprints:
    - af90d1ce99ba37aa79942617f75cd653
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - spec/
    - frontend/
    config:
      languages:
      - ruby
      - javascript
    exclude_fingerprints:
    - c6a87e201524a88b1787c8d2a41d54f0
    - 9115c821423dcaa2a62081cf99e9b61c
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .jsx
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 3eb892f98b02dbc460174276a4cde4b6
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.json"
  - "**.scss"
exclude_paths:
- config/
- db/
- vendor/
