---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - spec/
    - frontend/
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .jsx
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.json"
  - "**.scss"
exclude_paths:
- config/
- db/
- vendor/
