language: ruby

dist: trusty

rvm:
  - '2.3.1'

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

cache:
  bundler: true

before_install:
  - sed -i 's#https://ruby.taobao.org#https://rubygems.org#' Gemfile Gemfile.lock
  - cp config/app.yml.example config/app.yml

install:
  - bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec spec

