language: ruby

rvm:
  - '2.3.1'

services:
  - postgresql

cache:
  bundler: true

before_install:
  - sed -i 's#https://ruby.taobao.org#https://rubygems.org#' Gemfile Gemfile.lock

install:
  - bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec spec
  - bundle exec rspec codeclimate-test-reporter; true

